In [3]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [4]:
sent = ['The car is driven on the road',
        'The truck is driven on the road',  
        'The bike is driven on the road',
        'The bus is driven on the road',
        'The train is driven on the road',
        'The plane is driven on the road',
        'The boat is driven on the road',
        'The scooter is driven on the road',
        'The motorcycle is driven on the road',
        'The van is driven on the road']    


In [22]:
##Defining vocabulary size
vocab_size = 10000
##One hot representation
onehot_repr = [one_hot(words, vocab_size) for words in sent]
##Print one hot representation
for i in onehot_repr:
    print(i)    

[611, 611, 4595, 3132, 2330, 611, 5775]
[611, 7460, 4595, 3132, 2330, 611, 5775]
[611, 1102, 4595, 3132, 2330, 611, 5775]
[611, 7917, 4595, 3132, 2330, 611, 5775]
[611, 2719, 4595, 3132, 2330, 611, 5775]
[611, 3826, 4595, 3132, 2330, 611, 5775]
[611, 2836, 4595, 3132, 2330, 611, 5775]
[611, 9636, 4595, 3132, 2330, 611, 5775]
[611, 8310, 4595, 3132, 2330, 611, 5775]
[611, 5965, 4595, 3132, 2330, 611, 5775]


In [23]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences   
import numpy as np  



In [24]:
# Define the embedding layer
sentence_length = 10  # Length of each input sequence
# Assuming vocab_size is defined as the number of unique words in your dataset
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0  611  611 4595 3132 2330  611 5775]
 [   0    0    0  611 7460 4595 3132 2330  611 5775]
 [   0    0    0  611 1102 4595 3132 2330  611 5775]
 [   0    0    0  611 7917 4595 3132 2330  611 5775]
 [   0    0    0  611 2719 4595 3132 2330  611 5775]
 [   0    0    0  611 3826 4595 3132 2330  611 5775]
 [   0    0    0  611 2836 4595 3132 2330  611 5775]
 [   0    0    0  611 9636 4595 3132 2330  611 5775]
 [   0    0    0  611 8310 4595 3132 2330  611 5775]
 [   0    0    0  611 5965 4595 3132 2330  611 5775]]


In [36]:
embedding_dim = 100  # Dimension of the embedding vector
embedding_layer = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=10)        


c:\Users\sande\Documents\GitHub\RNN_Project_LLM\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [37]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=sentence_length))
model.build(input_shape=(None, sentence_length))  # <-- Add this line
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_14 (Embedding)        │ (None, 10, 100)        │     1,000,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,000,000 (3.81 MB)

 Trainable params: 1,000,000 (3.81 MB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[-0.03870051,  0.00078052,  0.02696693, ...,  0.03052222,
          0.01184867,  0.01352989],
        [-0.03870051,  0.00078052,  0.02696693, ...,  0.03052222,
          0.01184867,  0.01352989],
        [-0.03870051,  0.00078052,  0.02696693, ...,  0.03052222,
          0.01184867,  0.01352989],
        ...,
        [ 0.01491806,  0.04626426, -0.04026644, ..., -0.02908311,
          0.00036962,  0.0381987 ],
        [ 0.01172408,  0.02634517, -0.03410791, ...,  0.0244877 ,
          0.04187185, -0.02572525],
        [-0.0306631 ,  0.03444386, -0.0244224 , ..., -0.00113638,
         -0.04995039,  0.03550914]],

       [[-0.03870051,  0.00078052,  0.02696693, ...,  0.03052222,
          0.01184867,  0.01352989],
        [-0.03870051,  0.00078052,  0.02696693, ...,  0.03052222,
          0.01184867,  0.01352989],
        [-0.03870051,  0.00078052,  0.02696693, ...,  0.03052222,
          0.01184867,  0.01352989],
        ...,
        [ 0.01491806,  0.04626426, -0.04026644, ..., -